// flow-typed signature: 0cb7bf6fe23675b4690ad99c51a63b11
// flow-typed version: <<STUB>>/init-preset-node_v^6.8.5/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'init-preset-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'init-preset-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'init-preset-node/index' {
  declare module.exports: $Exports<'init-preset-node'>;
}
declare module 'init-preset-node/index.js' {
  declare module.exports: $Exports<'init-preset-node'>;
}
